sudo: required

language: java

services:
  - docker
  
branches:
  only:
    - master

install: true

script:
  - ./gradlew -DTRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER :tagLatest

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ; docker push sogis/heatdrill:latest
    on:
      branch: master