sudo: required

language: java

services:
  - docker
  
branches:
  only:
    - master

install: true

script:
  - ./gradlew -DTRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER :tagImage
     
after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push sogis/heatdrill:latest
  - docker push sogis/heatdrill:$TRAVIS_BUILD_NUMBER
  - docker push sogis/heatdrill_mockdb